"use client";

import bank from "@/data/stingers.json";
import { audioContext, isMuted } from "@/lib/audio";

/**
 * Live commentary: the ringside voice reacting to what the AI just said.
 *
 * Two layers, because latency is the whole problem. A bespoke ElevenLabs read
 * takes a second or two to come back, and a reaction that arrives two seconds
 * late is not a reaction. So:
 *
 *  1. A **pre-voiced stinger** fires the instant the text lands ("Oh! He did
 *     not just say that!"). Zero network, zero cost, generated by
 *     `scripts/stingers.mjs`.
 *  2. The **bespoke read** of the actual line follows, synthesised as it
 *     streams: the moment the model finishes its first sentence we start
 *     voicing that sentence, rather than waiting for the whole paragraph. The
 *     character cost is identical — it is the same words either way — but the
 *     voice starts roughly a full generation earlier.
 *
 * Clips are queued and played back to back so the two layers never talk over
 * each other, and everything degrades silently: no key, no budget, no network,
 * you still get the stinger, and if that fails too you still get the text.
 */

interface Clip {
  text: string;
  file: string;
}

const GROUPS = (bank as { groups: Record<string, Clip[]> }).groups;

export type Stinger = keyof typeof GROUPS & string;

const decoded = new Map<string, AudioBuffer>();
/** Text → in-flight or settled live read. Doubles as the prefetch cache. */
const live = new Map<string, Promise<AudioBuffer | null>>();

let lastPicked: Record<string, string> = {};
let generation = 0;
let playing: AudioBufferSourceNode[] = [];
/** When the currently queued audio finishes, in context time. */
let queueEndsAt = 0;

/** Whether the live voice budget is spent. Set by the first 402 we see. */
let liveExhausted = false;

function ctx() {
  return audioContext();
}

async function decodeUrl(url: string): Promise<AudioBuffer | null> {
  const c = ctx();
  if (!c) return null;
  const hit = decoded.get(url);
  if (hit) return hit;
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const buf = await c.decodeAudioData(await res.arrayBuffer());
    decoded.set(url, buf);
    return buf;
  } catch {
    return null;
  }
}

/** Stops anything the commentator is currently saying. */
export function stopCommentary(): void {
  generation++;
  queueEndsAt = 0;
  for (const s of playing) {
    try {
      s.stop();
    } catch {
      /* already finished */
    }
  }
  playing = [];
}

/**
 * Queues a buffer after whatever is already playing. Sequencing through the
 * context clock rather than setTimeout keeps the joins tight — a stinger and
 * the line after it should sound like one commentator, not two.
 */
function enqueue(buf: AudioBuffer, gen: number, gain = 1): void {
  const c = ctx();
  if (!c || gen !== generation || isMuted()) return;

  const start = Math.max(c.currentTime + 0.04, queueEndsAt - 0.05);
  const src = c.createBufferSource();
  src.buffer = buf;
  const g = c.createGain();
  g.gain.setValueAtTime(0.0001, start);
  g.gain.exponentialRampToValueAtTime(gain, start + 0.03);
  g.gain.setValueAtTime(gain, start + Math.max(0.05, buf.duration - 0.06));
  g.gain.exponentialRampToValueAtTime(0.0001, start + buf.duration);
  src.connect(g).connect(c.destination);
  src.start(start);
  playing.push(src);
  queueEndsAt = start + buf.duration;
}

/** Picks a line from a group, avoiding an immediate repeat. */
function pick(group: string): Clip | null {
  const clips = GROUPS[group];
  if (!clips?.length) return null;
  if (clips.length === 1) return clips[0];
  const options = clips.filter((c) => c.file !== lastPicked[group]);
  const chosen = options[Math.floor(Math.random() * options.length)] ?? clips[0];
  lastPicked = { ...lastPicked, [group]: chosen.file };
  return chosen;
}

/**
 * Fires a pre-voiced reaction immediately. Returns the transcript so the UI
 * can subtitle it even when the audio is muted or missing.
 */
export async function playStinger(group: Stinger, { cut = true } = {}): Promise<string> {
  const clip = pick(group);
  if (!clip) return "";
  if (cut) stopCommentary();
  const gen = generation;
  if (isMuted()) return clip.text;
  const c = ctx();
  if (c?.state === "suspended") await c.resume().catch(() => {});
  const buf = await decodeUrl(clip.file);
  if (buf) enqueue(buf, gen, 0.95);
  return clip.text;
}

/** Requests a bespoke read, sharing one request between prefetch and playback. */
function fetchLive(text: string): Promise<AudioBuffer | null> {
  const key = text.trim();
  const existing = live.get(key);
  if (existing) return existing;

  const p = (async (): Promise<AudioBuffer | null> => {
    if (liveExhausted) return null;
    const c = ctx();
    if (!c) return null;
    try {
      const res = await fetch("/api/say", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text: key }),
      });
      if (res.status === 402) {
        // Budget gone for the rest of the session — stop asking.
        liveExhausted = true;
        return null;
      }
      if (!res.ok) return null;
      return await c.decodeAudioData(await res.arrayBuffer());
    } catch {
      return null;
    }
  })();

  live.set(key, p);
  return p;
}

/** Warms a read we expect to want shortly. Safe to call speculatively. */
export function prefetchLine(text: string): void {
  const clean = text.trim();
  if (clean.length > 8 && !liveExhausted) void fetchLive(clean);
}

export function liveVoiceExhausted(): boolean {
  return liveExhausted;
}

/** Shortest fragment worth its own request — below this, wait for more text. */
const MIN_SEGMENT = 45;

/**
 * The whole reaction in one call: stinger now, bespoke read behind it.
 *
 * `stream` is handed a callback it should invoke with the accumulated text as
 * it arrives, and should resolve with the final text.
 */
export async function commentate(
  group: Stinger,
  stream: (onText: (accumulated: string) => void) => Promise<string>,
): Promise<{ stinger: string; spoken: string }> {
  stopCommentary();
  const gen = generation;
  const stinger = await playStinger(group, { cut: false });

  let consumed = 0;
  let chain: Promise<void> = Promise.resolve();

  const speak = (segment: string) => {
    const text = segment.trim();
    if (text.length < 4) return;
    const pending = fetchLive(text);
    chain = chain.then(async () => {
      const buf = await pending;
      if (buf && gen === generation) enqueue(buf, gen, 1);
    });
  };

  const final = await stream((accumulated) => {
    if (gen !== generation) return;
    const tail = accumulated.slice(consumed);
    const boundary = [...tail.matchAll(/[.!?]["')\]]?(\s|$)/g)].pop();
    if (!boundary || boundary.index === undefined) return;
    const end = boundary.index + boundary[0].length;
    if (end < MIN_SEGMENT) return;
    speak(tail.slice(0, end));
    consumed += end;
  });

  if (gen === generation) speak(final.slice(consumed));
  await chain;
  return { stinger, spoken: final };
}
